version: "3.10"

services:

  app:
    container_name: app
    build: .
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:6.2-alpine

  celery_worker:
    container_name: celery_worker
    build: .
    command: bash -c "poetry run celery -A  celery_service.celery.celery_app worker --loglevel=info"
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: bash -c "poetry run celery -A  celery_service.celery.celery_app flower"
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - CELERY_RESULT_BACKEND=${REDIS_URL}
    depends_on:
      - app
      - redis
      - celery_worker

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
